import { useEffect, useState } from 'react';

/**
 * TrainingHistoryPanel
 *
 * Shows a high-level summary of offline DQN training.
 * Expects a small JSON summary file generated by the Python
 * training pipeline (e.g. aggregated from Monitor logs):
 *
 *   /dqn/training_summary.json
 *
 * If the file is missing, the panel gracefully shows a
 * placeholder message so classroom use is never blocked.
 */
export default function TrainingHistoryPanel() {
    const [summary, setSummary] = useState(null);
    const [error, setError] = useState(null);

    useEffect(() => {
        let cancelled = false;

        fetch('/dqn/training_summary.json', { cache: 'no-store' })
            .then((res) => {
                if (!res.ok) throw new Error(`HTTP ${res.status}`);
                return res.json();
            })
            .then((json) => {
                if (!cancelled) setSummary(json);
            })
            .catch((err) => {
                if (!cancelled) setError(err);
            });

        return () => {
            cancelled = true;
        };
    }, []);

    return (
        <div style={{ marginTop: '15px' }}>
            <h3 style={{ fontSize: '12px', color: '#ffaa44', margin: '0 0 5px 0' }}>TRAINING HISTORY</h3>
            <div style={{
                background: 'rgba(0,0,0,0.5)',
                padding: '8px',
                borderRadius: '4px',
                fontSize: '11px',
                border: '1px solid rgba(255,170,68,0.4)',
            }}>
                {!summary && !error && (
                    <div style={{ opacity: 0.7 }}>
                        Loading offline training summary...
                    </div>
                )}

                {error && !summary && (
                    <div style={{ opacity: 0.7 }}>
                        Offline training summary not available yet. Run the Python training
                        pipeline and publish <code>/dqn/training_summary.json</code> to enable this panel.
                    </div>
                )}

                {summary && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                        <div>Total episodes: <strong>{summary.total_episodes}</strong></div>
                        <div>Mean reward: <strong>{summary.mean_reward?.toFixed(2)}</strong></div>
                        <div>Final collision rate: <strong>{(summary.collision_rate * 100).toFixed(1)}%</strong></div>
                        <div>Final red-light violation rate: <strong>{(summary.red_light_rate * 100).toFixed(1)}%</strong></div>
                        <div style={{ opacity: 0.8, marginTop: '4px' }}>
                            This AI has already practiced many episodes offline; you are seeing the
                            behavior of that trained policy in this run.
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
}

